name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

permissions:
  contents: write  # Allow write access to the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure this is set to a compatible version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f out  # Force add the out directory
          git commit -m "Deploy to GitHub Pages" || echo "No changes to commit"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/nyumatlab/nyumatlab.github.io.git" main:gh-pages
